server:
  port: 8081

spring:
  application:
  name: spring-ai-alibaba-deepseek-chat-model-example
  ai:
    deepseek:
      api-key: ${deepseek_api}
      base-url: "https://api.deepseek.com"
      chat:
        options:
          model: deepseek-chat
      embedding:
        enabled: false
    mcp:
      client:
        type: ASYNC
        stdio:
          servers-configuration: classpath:/mcp-servers-config.json